name: HTML Check

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Requried will all actions
      - name: Checks HTML5
        uses: Cyb3r-Jak3/html5validator-action@v7.2.0
        with:
          root: src/
